# Generated by Django 5.0.2 on 2024-03-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Contact',
        ),
    ]
